<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks></TargetFrameworks>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TUnit" Version="1.64.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SDK.CSharp.Hub\SDK.CSharp.Hub.csproj"/>
        <ProjectReference Include="..\SDK.CSharp.Live\SDK.CSharp.Live.csproj"/>
        <ProjectReference Include="..\SDK.CSharp\SDK.CSharp.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="ApiMockResponses\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
