<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.12" />
        <PackageReference Include="PolySharp" Version="1.16.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Condition=" '$(Configuration)' == 'Release' " Include="OpenShock.SDK.CSharp" Version="$(Version)"/>
        <PackageReference Include="Semver" Version="3.0.0"/>
    </ItemGroup>

    <ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
        <ProjectReference Include="..\SDK.CSharp\SDK.CSharp.csproj"/>
    </ItemGroup>
</Project>
